name: Update Movie Credits Workflow

on:
  workflow_dispatch:  # Triggered manually via the GitHub Actions tab or an API call

jobs:
  update_credits:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Fetch team and credits from Node API
      - name: Fetch team and credits from Node API
        run: |
          echo "progress=Fetching team and credits..." >> $GITHUB_ENV
          curl -s --request GET ${{ secrets.NODE_API_URL }}/getTeamAndCredits > team_and_credits.json
          echo "Step 1 complete: Fetched credits"

      # Step 5: Scrape IMDb for new credits
      - name: Scrape IMDb for new credits
        run: |
          echo "progress=Scraping IMDb for credits..." >> $GITHUB_ENV
          python update_barn.py team_and_credits.json  # Passing the file to the script
          echo "Step 2 complete: Scraped IMDb data"

      # Step 6: Update Node API with new credits
      - name: Update Node API with new credits
        run: |
          echo "progress=Updating database with new credits..." >> $GITHUB_ENV
          curl -X POST ${{ secrets.NODE_API_URL }}/updateCredits \
          -H "Content-Type: application/json" \
          --data @new_credits.json > api_response.json
          echo "progress=Database updated successfully!" >> $GITHUB_ENV

      # Step 7: Set final output with new titles
      - name: Set final output
        id: set_output
        run: |
          echo "new_titles=$(cat api_response.json | jq -r '.newTitles')" >> $GITHUB_ENV
          echo "progress=Process completed successfully!" >> $GITHUB_ENV
